imports:
  - https://raw.githubusercontent.com/dotnet/crank/main/src/Microsoft.Crank.Jobs.Bombardier/bombardier.yml

jobs:

  server:
    sources:
      functionshost:
        repository: https://github.com/Azure/azure-functions-host
        branchOrCommit: dev
    project: functionshost/src/WebJobs.Script.WebHost/WebJobs.Script.WebHost.csproj
    readyStateText: 'Application started.'
    environmentVariables:
      AZURE_FUNCTIONS_ENVIRONMENT: Development
      FUNCTIONS_WORKER_RUNTIME: dotnet-isolated
      ASPNETCORE_ENVIRONMENT: Development
      AzureWebJobsScriptRoot: D:\apps\crank\hello_http

scenarios:
  hellohttp:
    hostruntime:
      job: server
        
    load:
      job: bombardier
      variables:
        serverPort: 5000
        path: /api/HelloHttp

profiles:
  win-devbox:
    variables:
      serverAddress: localhost
    jobs: 
      hostruntime:
        endpoints: 
          - http://localhost:5010
      load:
        endpoints: 
          - http://localhost:5010
