trigger:
  branches:
    include:
    - shkr/crank-scenario-file

# CI only, does not trigger on PRs.
pr: none

variables:
  connection: 'AzureServiceBusConnection'  
  serviceBusQueueName: ''
  serviceBusNamespace: ''
  arguments: '--verbose'

jobs:
- job: PublishToServiceBus
  pool:
    name: 1es-pool-azfunc
    vmImage: 1es-windows-2022
  steps:
    - task: PublishToAzureServiceBus@1
      displayName: "Publish To Azure ServiceBus"
      inputs:
        azureSubscription: ${{ variables.connection }}
        serviceBusQueueName: ${{ variables.serviceBusQueueName }}
        serviceBusNamespace: ${{ variables.serviceBusNamespace }}
        waitForCompletion: true
        useDataContractSerializer: "false"
        messageBody: |
          {
            "name": "crank",
            "retries": 1,
            "args": [ "${{ variables.arguments }} --variable foo=30" ]
          }
