trigger:
  branches:
    include:
    - shkr/crank-scenario-file

# CI only, does not trigger on PRs.
pr: none

parameters:
  connection: ''
  serviceBusQueueName: ''
  serviceBusNamespace: ''
  arguments: ''

jobs:
- job: PublishToServiceBus
  pool:
    name: 1es-pool-azfunc
    vmImage: 1es-windows-2022
  steps:
    - task: PublishToAzureServiceBus@2
      condition: succeededOrFailed()
      timeoutInMinutes: 10
      displayName: "Publish To AzureServiceBus"
      inputs:
        connectedServiceName: ${{ parameters.connection }}
        serviceBusQueueName: ${{ parameters.serviceBusQueueName }}
        serviceBusNamespace: ${{ parameters.serviceBusNamespace }}
        waitForCompletion: true
        useDataContractSerializer: "false"
        messageBody: |
          {
            "name": "crank",
            "retries": 1,
            "args": [ "${{ parameters.arguments }} --variable foo=30" ]
          }
