trigger:
  branches:
    include:
    - shkr/crank-scenario-file

# CI only, does not trigger on PRs.
pr: none

variables:
  connection: '$(connection)'  
  serviceBusQueueName: '$(serviceBusQueueName)'
  serviceBusNamespace: '$(serviceBusNamespace)'
  arguments: '--verbose'

jobs:
- job: PublishToServiceBus
  pool: server
  steps:
    - task: PublishToAzureServiceBus@2
      displayName: "Publish To Azure ServiceBus"
      inputs:
        azureSubscription: $(connection)
        serviceBusQueueName: ${{ variables.serviceBusQueueName }}
        serviceBusNamespace: '$(serviceBusNamespace)'
        waitForCompletion: true
        useDataContractSerializer: "false"
        messageBody: |
          {
            "name": "crank",
            "retries": 1,
            "args": [ "${{ variables.arguments }} --variable foo=30" ]
          }
