trigger:
  branches:
    include:
    - shkr/crank-scenario-file

# CI only, does not trigger on PRs.
pr: none

variables:
  arguments: '--verbose'

jobs:
- job: PublishToServiceBus
  displayName: "Windows HTTP Tests"
  pool: server
  steps:
    - task: PublishToAzureServiceBus@2
      displayName: ".NET9 Hello Http"
      inputs:
        azureSubscription: Azure-Functions-Host-Perf-internal
        serviceBusQueueName: dni9-hello-http
        serviceBusNamespace: azure-functions-host-perf
        waitForCompletion: true
        useDataContractSerializer: "false"
        messageBody: |
          {
            "name": "crank",
            "retries": 1,
            "args": [ "--config https://raw.githubusercontent.com/kshyju/temp-perf-scenarios/refs/heads/main/hellohttp.yml --scenario hellohttp --profile win2022 --description net9hellohttpwin --chart --verbose" ]
          }
